dataset:
  train_csv: "datasets/UNSW_NB15_training-set.csv"          #modificare con tutti i dataset
  test_csv: "datasets/UNSW_NB15_testing-set.csv"

benchmark:
  mode: "incremental"     # ["fixed", "incremental"] 
  param: 2         #single mode: fixed and param = 1 

strategy: "DER"         #ICaRL, Replay, DER

preprocessing:
  drop_columns: ["id", "label"]
  categorical: ["proto", "service", "state"]
  label_column: "attack_cat"
  clip_percentile: 0.99
  add_features: true
  balance_classes: true   # puoi metterlo true

output:
  save_preprocessor: "artifacts/preprocessor.pkl"
  save_label_encoder: "artifacts/label_encoder.pkl"
